global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # API Node service metrics
  - job_name: 'api-node'
    static_configs:
      - targets: ['api-node:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Data service metrics  
  - job_name: 'data-service'
    static_configs:
      - targets: ['data-service:4000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Frontend service metrics
  - job_name: 'web-react'
    static_configs:
      - targets: ['web-react:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MongoDB exporter (we'll add this later)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # Redis exporter  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
